{"name": "Verify user gets error for incorrect password", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: invalid locator\n  (Session info: chrome=140.0.7339.81)\nStacktrace:\n\tGetHandleVerifier [0x0x7ff6918f1eb5+80197]\n\tGetHandleVerifier [0x0x7ff6918f1f10+80288]\n\t(No symbol) [0x0x7ff6916702fa]\n\t(No symbol) [0x0x7ff6916c7a9e]\n\t(No symbol) [0x0x7ff6916c7f9c]\n\t(No symbol) [0x0x7ff69171ba87]\n\t(No symbol) [0x0x7ff6916f03bf]\n\t(No symbol) [0x0x7ff6917187fb]\n\t(No symbol) [0x0x7ff6916f0153]\n\t(No symbol) [0x0x7ff6916b8b02]\n\t(No symbol) [0x0x7ff6916b98d3]\n\tGetHandleVerifier [0x0x7ff691bae83d+2949837]\n\tGetHandleVerifier [0x0x7ff691ba8c6a+2926330]\n\tGetHandleVerifier [0x0x7ff691bc86c7+3055959]\n\tGetHandleVerifier [0x0x7ff69190cfee+191102]\n\tGetHandleVerifier [0x0x7ff6919150af+224063]\n\tGetHandleVerifier [0x0x7ff6918faf64+117236]\n\tGetHandleVerifier [0x0x7ff6918fb119+117673]\n\tGetHandleVerifier [0x0x7ff6918e10a8+11064]\n\tBaseThreadInitThunk [0x0x7ffa566ee8d7+23]\n\tRtlUserThreadStart [0x0x7ffa57848d9c+44]\n\n", "trace": "  File \"C:\\Users\\owash\\PycharmProjects\\Careerist\\python-selenium-automation\\.venv\\Lib\\site-packages\\behave\\model.py\", line 1991, in run\n    match.run(runner.context)\n    ~~~~~~~~~^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\owash\\PycharmProjects\\Careerist\\python-selenium-automation\\.venv\\Lib\\site-packages\\behave\\matchers.py\", line 105, in run\n    self.func(context, *args, **kwargs)\n    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"features\\steps\\sign_in_page_steps.py\", line 32, in verify_password_error_message\n    context.app.sign_in_page.verify_password_error_message()\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File \"C:\\Users\\owash\\PycharmProjects\\Careerist\\python-selenium-automation\\pages\\sign_in_page.py\", line 45, in verify_password_error_message\n    self.verify_partial_text(*self.PW_ERROR_MSG)\n    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\owash\\PycharmProjects\\Careerist\\python-selenium-automation\\pages\\base_page.py\", line 74, in verify_partial_text\n    actual_text = self.find_element(*locator).text\n                  ~~~~~~~~~~~~~~~~~^^^^^^^^^^\n  File \"C:\\Users\\owash\\PycharmProjects\\Careerist\\python-selenium-automation\\pages\\base_page.py\", line 16, in find_element\n    return self.driver.find_element(*locator)\n           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^\n  File \"C:\\Users\\owash\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 914, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\owash\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 447, in execute\n    self.error_handler.check_response(response)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^\n  File \"C:\\Users\\owash\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Given Open target home page", "status": "passed", "start": 1759441995820, "stop": 1759442000885}, {"name": "When Click the account button sign in button opens", "status": "passed", "start": 1759442000885, "stop": 1759442001081}, {"name": "Then Click sign in button", "status": "passed", "start": 1759442001081, "stop": 1759442001891}, {"name": "And Enter user morvitalgr@edgetopgrid.com", "status": "passed", "start": 1759442001891, "stop": 1759442002781}, {"name": "And Click sign in by password button", "status": "passed", "start": 1759442002781, "stop": 1759442003332}, {"name": "And Enter password Testers2", "status": "passed", "start": 1759442003332, "stop": 1759442003487}, {"name": "Then Verify password error message is shown", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: invalid locator\n  (Session info: chrome=140.0.7339.81)\nStacktrace:\n\tGetHandleVerifier [0x0x7ff6918f1eb5+80197]\n\tGetHandleVerifier [0x0x7ff6918f1f10+80288]\n\t(No symbol) [0x0x7ff6916702fa]\n\t(No symbol) [0x0x7ff6916c7a9e]\n\t(No symbol) [0x0x7ff6916c7f9c]\n\t(No symbol) [0x0x7ff69171ba87]\n\t(No symbol) [0x0x7ff6916f03bf]\n\t(No symbol) [0x0x7ff6917187fb]\n\t(No symbol) [0x0x7ff6916f0153]\n\t(No symbol) [0x0x7ff6916b8b02]\n\t(No symbol) [0x0x7ff6916b98d3]\n\tGetHandleVerifier [0x0x7ff691bae83d+2949837]\n\tGetHandleVerifier [0x0x7ff691ba8c6a+2926330]\n\tGetHandleVerifier [0x0x7ff691bc86c7+3055959]\n\tGetHandleVerifier [0x0x7ff69190cfee+191102]\n\tGetHandleVerifier [0x0x7ff6919150af+224063]\n\tGetHandleVerifier [0x0x7ff6918faf64+117236]\n\tGetHandleVerifier [0x0x7ff6918fb119+117673]\n\tGetHandleVerifier [0x0x7ff6918e10a8+11064]\n\tBaseThreadInitThunk [0x0x7ffa566ee8d7+23]\n\tRtlUserThreadStart [0x0x7ffa57848d9c+44]\n\n", "trace": "  File \"C:\\Users\\owash\\PycharmProjects\\Careerist\\python-selenium-automation\\.venv\\Lib\\site-packages\\behave\\model.py\", line 1991, in run\n    match.run(runner.context)\n    ~~~~~~~~~^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\owash\\PycharmProjects\\Careerist\\python-selenium-automation\\.venv\\Lib\\site-packages\\behave\\matchers.py\", line 105, in run\n    self.func(context, *args, **kwargs)\n    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"features\\steps\\sign_in_page_steps.py\", line 32, in verify_password_error_message\n    context.app.sign_in_page.verify_password_error_message()\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File \"C:\\Users\\owash\\PycharmProjects\\Careerist\\python-selenium-automation\\pages\\sign_in_page.py\", line 45, in verify_password_error_message\n    self.verify_partial_text(*self.PW_ERROR_MSG)\n    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\owash\\PycharmProjects\\Careerist\\python-selenium-automation\\pages\\base_page.py\", line 74, in verify_partial_text\n    actual_text = self.find_element(*locator).text\n                  ~~~~~~~~~~~~~~~~~^^^^^^^^^^\n  File \"C:\\Users\\owash\\PycharmProjects\\Careerist\\python-selenium-automation\\pages\\base_page.py\", line 16, in find_element\n    return self.driver.find_element(*locator)\n           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^\n  File \"C:\\Users\\owash\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 914, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\owash\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 447, in execute\n    self.error_handler.check_response(response)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^\n  File \"C:\\Users\\owash\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1759442003487, "stop": 1759442003763}], "start": 1759441993965, "stop": 1759442006003, "uuid": "1ecb6433-b082-4a9b-ad1d-4a0b368d4c85", "historyId": "e154cabed1a62f82a0be90244767e3a7", "fullName": "Test login page: Verify user gets error for incorrect password", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Test login page"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}], "titlePath": ["features", "tests", "Test login page"]}